-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.users
(
    user_id integer NOT NULL,
    email character varying(50)[] NOT NULL,
    password character varying(50)[] NOT NULL,
    status boolean NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.system_staffs
(
    staff_id integer NOT NULL,
    user_id integer NOT NULL,
    first_name character varying(50)[] NOT NULL,
    last_name character varying(50)[] NOT NULL,
    PRIMARY KEY (staff_id)
);

CREATE TABLE public.job_seekers
(
    job_seeker_id integer NOT NULL,
    user_id integer NOT NULL,
    first_name character varying(50)[] NOT NULL,
    las_name character varying(50)[] NOT NULL,
    birth_date date NOT NULL,
    PRIMARY KEY (job_seeker_id)
);

CREATE TABLE public.employers
(
    employer_id integer NOT NULL,
    user_id integer NOT NULL,
    company_name character varying(50)[] NOT NULL,
    web_site character varying(50)[] NOT NULL,
    phone_number character varying(11)[] NOT NULL,
    PRIMARY KEY (employer_id)
);

CREATE TABLE public.job_applications
(
    application_id integer NOT NULL,
    job_seeker_id integer NOT NULL,
    job_advertisement_id integer NOT NULL,
    PRIMARY KEY (application_id)
);

CREATE TABLE public.job_positions
(
    job_position_id integer NOT NULL,
    job_position_name character varying(50)[] NOT NULL,
    PRIMARY KEY (job_position_id)
);

CREATE TABLE public.job_advertisements
(
    job_advertisement_id integer NOT NULL,
    employer_id integer NOT NULL,
    job_position_id integer NOT NULL,
    PRIMARY KEY (job_advertisement_id)
);

ALTER TABLE public.system_staffs
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id)
    NOT VALID;


ALTER TABLE public.job_applications
    ADD FOREIGN KEY (job_seeker_id)
    REFERENCES public.job_seekers (job_seeker_id)
    NOT VALID;


ALTER TABLE public.job_applications
    ADD FOREIGN KEY (job_advertisement_id)
    REFERENCES public.job_advertisements (job_advertisement_id)
    NOT VALID;


ALTER TABLE public.job_advertisements
    ADD FOREIGN KEY (job_position_id)
    REFERENCES public.job_positions (job_position_id)
    NOT VALID;

END;
